import { motion } from 'framer-motion';

const StatsGridSection = () => {
    return (
        <section className="w-full py-32 px-6 bg-[#050505] flex justify-center">
            <div className="max-w-7xl w-full">

                <motion.div
                    initial={{ opacity: 0 }}
                    whileInView={{ opacity: 1 }}
                    viewport={{ once: true }}
                    className="text-center mb-16"
                >
                    <h2 className="text-3xl font-bold text-white mb-4">Why Now?</h2>
                    <p className="text-white/50">The industry is shifting. Don't get left behind.</p>
                </motion.div>

                <div className="grid grid-cols-1 md:grid-cols-6 md:grid-rows-2 gap-4 h-auto md:h-[600px]">

                    {/* Card 1: Large - 80% AI Code */}
                    <motion.div
                        initial={{ opacity: 0, scale: 0.95 }}
                        whileInView={{ opacity: 1, scale: 1 }}
                        viewport={{ once: true }}
                        className="md:col-span-4 md:row-span-2 bg-[#0a0a0a] rounded-3xl p-10 border border-white/5 flex flex-col justify-between relative overflow-hidden group"
                    >
                        <div className="absolute inset-0 bg-gradient-to-br from-red-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-700" />

                        <div>
                            <p className="text-white/40 font-mono text-sm uppercase mb-4">Market Shift</p>
                            <h3 className="text-6xl md:text-8xl font-black text-white tracking-tighter">
                                80<span className="text-red-500">%</span>
                            </h3>
                        </div>

                        <div>
                            <p className="text-2xl text-white font-medium max-w-md leading-tight">
                                of all code will be AI-generated by 2027, according to Gartner.
                            </p>
                            <p className="mt-6 text-white/30 text-sm">Source: Gartner Report 2024</p>
                        </div>
                    </motion.div>

                    {/* Card 2: Top Right - Speed */}
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ delay: 0.1 }}
                        className="md:col-span-2 md:row-span-1 bg-[#111] rounded-3xl p-8 border border-white/5 flex flex-col justify-center items-center text-center group"
                    >
                        <span className="text-5xl font-black text-white mb-2 group-hover:scale-110 transition-transform duration-300">10x</span>
                        <p className="text-white/60 font-medium">Faster Development</p>
                    </motion.div>

                    {/* Card 3: Bottom Right - Cost */}
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ delay: 0.2 }}
                        className="md:col-span-2 md:row-span-1 bg-white text-black rounded-3xl p-8 flex flex-col justify-center items-center text-center relative overflow-hidden"
                    >
                        <span className="text-5xl font-black text-black z-10">$0</span>
                        <p className="text-black/60 font-medium z-10 w-32 mx-auto">Cost to start building</p>

                        {/* Decorative element */}
                        <div className="absolute -right-4 -bottom-4 w-24 h-24 bg-red-500 rounded-full blur-xl opacity-20" />
                    </motion.div>

                </div>
            </div>
        </section>
    );
};

export default StatsGridSection;
